### ISSUE TITLE
What is the format that i need to save in B in the AX=YB

### ISSUE THREAD

**Issue by SakethTecholution** [Rooholla-KhorramBakht/SimpleHandEye#2]
Firstly this is amazing work you have done . i have very small question. Using my robot( doosan cobot) python library i can get x,y,z,a,b,c(euler angles) . what is the format does opencv expects for solving the problem. If possible can you please let me know i am very new to this

**Comment by SakethTecholution** [comment]
cc @BolunDai0216 @Rooholla-KhorramBakht

**Comment by Rooholla-KhorramBakht** [comment]
Hi, Thanks for your interest in the project. As described in the main readme page, the input to the solver is two lists of 4x4 numpy homogeneous transformation matrices. The meaning of these matrices are determined based on the type of the problem (three examples are provided in the documentation). For your case, you need to convert your Euler parameters and position vector to a homogeneous transformation matrix.
